### ISSUE TITLE
Default modules when no match was found

### ISSUE THREAD

**Issue by luigibarbato** [fedeizzo/rofi-spotlight#1]
### Considering that
The possible use for a custom script in the case of a match not found has been implemented.
### Considering that
Usually when the search is not successful it is because the keyword is not present among the resources available locally
### Proposal
Implement a module that is activated by default which asks the user whether to open a specific file manager or to search for the keyword through a common search engine (Google, DuckDuckgo, Bing etc.)

**Comment by fedeizzo** [comment]
Hi,

I write this feature (https://github.com/fedeizzo/rofi-spotlight/commit/5e15e255e27fe53498d2bc96e865196d7a387e87). When there isn't
`no match command`
option in config file google search engine is used by default. There is also the possibility to write duck and use duckduckgo
`no match command: duck`
